### ISSUE TITLE
MP4 video can not be display

### ISSUE THREAD

**Issue by jyy1082** [guysoft/FullPageOS#214] opened 2018-03-11 23:17 UTC
#### What were you doing?
I  installed omxplayer and run:
"omxplayer --win "0 0 799 479" /home/pi/video.mp4" 
the commands shows
![image](https://user-images.githubusercontent.com/8751908/37259738-94ae08c2-2560-11e8-8423-e6f24131ba94.png)
However, there is no video displaying on the screen. 

#### Version of FullPageOS?
0.8.1

**Comment by guysoft** [comment] 2018-03-12 00:41
I am not sure I can support this, this is a raspbian issue.
Its a duplicate of https://github.com/guysoft/FullPageOS/issues/167 . so same answer

**Comment by jyy1082** [comment] 2018-03-12 01:44
We would like to play a video when raspberry pi is booting and then going to chrome. Actually, FullPageOS 0.6 can allow me to implement it, but not 0.8.1. 
Do I need to downgrade to use 0.6 for that?

**Comment by guysoft** [comment] 2018-03-12 08:01
1. Can you provide how you implemented it in 0.6? I can't support code I can't see, and this is an open source project.
2. Who is "we"?

**Comment by jyy1082** [comment] 2018-03-12 19:55
In the 0.6, I added 
omxplayer --win "0 0 799 479" /home/pi/logo.mp4
in /etc/rc.local. 
The video can be played and displayed when booting.
However, I did same in 0.8.1. It does not work. There is no video display
![image](https://user-images.githubusercontent.com/8751908/37306228-6c43f452-260d-11e8-884e-96ac60c5527c.png)

**Comment by guysoft** [comment] 2018-03-12 22:31
0.6 is based on raspbian jessie. While 0.8.1 is based on raspbian stretch. The boot process from Jessie has changed from sysV to systemd and therefor the console looks diffrent. You will need to make your script support systemd. See internet - for example: https://askubuntu.com/questions/919054/how-do-i-run-a-single-command-at-startup-using-systemd

**Comment by jyy1082** [comment] 2018-03-12 22:34
Thank you! I will try that.

**Comment by guysoft** [comment] 2018-04-23 11:01
Any news?

**Comment by guysoft** [comment] 2018-06-11 14:59
Closing because no reply

**Closed by guysoft** 2018-06-11 14:59 UTC
