### ISSUE TITLE
Set up with static IP on eth on boot

### ISSUE THREAD

**Issue by charliwest** [guysoft/FullPageOS#231] opened 2018-05-11 14:41 UTC
#### What were you doing?
I would like to be able to boot first time to a WIRED connection with a static IP

I think this option used to be in fullpageos-network.txt but with wpa changes it is no longer an option.
#### Version of FullPageOS?
 0.9.0

**Comment by guysoft** [comment] 2018-05-11 14:45
Duplicate of #222

**Closed by guysoft** 2018-05-11 14:45 UTC

**Comment by charliwest** [comment] 2018-05-11 16:03
That other issue is about WiFi isn’t it? I am asking about eth0/wired connection

**Comment by guysoft** [comment] 2018-05-11 18:47
Ok, see https://github.com/guysoft/OctoPi/issues/202 
I can't really do anything beyond that. Its part of Raspbian.

**Comment by IT-Mase** [comment] 2024-05-29 10:16
Hi !
I had the same issue ...
Found an answer, for last version which is under raspbian bookworm [here](https://www.abelectronics.co.uk/kb/article/31/set-a-static-ip-address-on-raspberry-pi-os-bookworm) !
It worked like a charm for me !

Ciao !
