### ISSUE TITLE
Hi - is it possible to change the orientation to portrait instead of landscape ? I need the monitor to be vertical...

### ISSUE THREAD

**Issue by hurtigkarl** [guysoft/FullPageOS#407] opened 2022-02-24 12:43 UTC
#### What were you doing?

[Please be as specific as possible here]

#### Version of FullPageOS?

[Can be found in /etc/fullpageos_version ALWAYS INCLUDE.]

#### Screenshot(s) showing the problem:

[If applicable. Always include if unsure or reporting UI issues.]

**Comment by guysoft** [comment] 2022-02-27 12:57
Duplicate of: #386

**Closed by guysoft** 2022-02-27 12:57 UTC
