### ISSUE TITLE
Unable to refresh chromium on start

### ISSUE THREAD

**Issue by daveeyboy** [guysoft/FullPageOS#132] opened 2017-06-20 05:44 UTC
#### What were you doing?
Loading a web page with an addin on boot from fullpageos.txt
[Please be as specific as possible here]
Very very new at raspberry/ full page so bear with the new guy :) I can boot into a web page great however it doesn't appear to auto refresh the page, I actually need to hit f5 to do get the result, however I don't want a keyboard on it and don't want to touch it every time it reboots or powers off

Is there some way I can refresh or get to the dashboard to do that? How do I get in dashboard? Strike me down for my new ways, or send me to another forum :)

#### What did you expect to happen?
Load web page with addin, refreshes
#### What happened instead?
Loads with no refresh
#### Version of FullPageOS?
Latest I think
[Can be found in /etc/fullpageos_version ALWAYS INCLUDE.]
Not on me
#### Screenshot(s) showing the problem:

[If applicable. Always include if unsure or reporting UI issues.]

**Comment by guysoft** [comment] 2017-06-20 12:25
Duplicate of https://github.com/guysoft/FullPageOS/issues/127

**Closed by guysoft** 2017-06-20 12:25 UTC
