### ISSUE TITLE
Error 404 

### ISSUE THREAD

**Issue by sng1** [guysoft/FullPageOS#143] opened 2017-07-31 00:26 UTC
I saw this somewhere on here but can't find the thread.   Some pages I get Error 404 I know it's a HTTP request error.  Do URLs have to start with HTTP(S) to work with FullPageOS?  It seems that's what the issue is.  All URLs starting with HTTP(S) work fine but some I can only provide the www.google.com for example not HTTP available to be copied.

**Comment by guysoft** [comment] 2017-08-01 08:34
Duplicate of #31

**Closed by guysoft** 2017-08-01 08:34 UTC
