### ISSUE TITLE
Raspberry Pi Imager Download Issue.

### ISSUE THREAD

**Issue by MetaMysteries7** [guysoft/FullPageOS#516] opened 2024-02-12 03:12 UTC
Hello, I would like to let you know of an issue that has to do with FullPageOS from the Raspberry PI Imager. I was attempting to download and install it, but when getting the nightly from 2024, it responded with a corrupt download, and when downloading the nightly from 2023, a 404 error is given.

In order to reproduce this error, all you have to do is download the newest versions from the Raspberry pi imager.

If it is impossible to reproduce, then I might be having some issues on my personal computer. 

Another question on this issue, is something going on with the download, is it unofficial? I'm unsure what's going on in this case. There may also be a chance that if the download was official, then the website may have been hacked, or a version of the raspberry pi image was hacked. If you have any information on what may be going on, please let me know.

**Comment by guysoft** [comment] 2024-02-12 13:42
Duplicate of #497

Thanks for updating, I pushed a fix and it seems to still do taht

**Closed by guysoft** 2024-02-12 13:42 UTC
