### ISSUE TITLE
Cable or wifi in intranet

### ISSUE THREAD

**Issue by davisukin** [guysoft/FullPageOS#395] opened 2022-01-09 18:58 UTC
Hello,
I am newbie to raspberry.
I am trying to install a FullpageOS on a raspberry within an intranet, which uses static ip.
I have all of info: ip, wateway. dns, but I don't know where / how to put them.
The raspberry can be connected to inet via cable or wifi.
The tests outside the intranet (in my house) have been satisfactory since I use wifi with dhcp configured in "fullpageos-wpa-supplicanty.txt" and the page to be viewed is a public website.

Regards.

#### Version of FullPageOS?

2021-03-04-fullpageos-buster-armhf-lite-0.12.0

**Comment by guysoft** [comment] 2022-01-09 19:13
What is your question?

**Comment by davisukin** [comment] 2022-01-09 20:22
How to configure a static ip.
Can i do in the fullpageos-wpa-supplicanty.txt for the wifi?
How cain i do for cable'

**Comment by guysoft** [comment] 2022-01-09 20:42
Duplicate of #222
See https://community.octoprint.org/t/static-ip-adress-for-wifi-and-cable-is-done/5600/2
You can't set static IP in wpa-supplicant because wpa-supplicant is part of the wireless encryption system and not part of the IP handling system. It goes in ``/etc/dhcpcd.conf``

**Closed by guysoft** 2022-01-09 20:42 UTC
