### ISSUE TITLE
Disable all chromium keyboard shortcuts / disable modifier keys so shortcuts can not be executed

### ISSUE THREAD

**Issue by svefro** [guysoft/FullPageOS#491] opened 2023-12-15 09:02 UTC
#### What were you doing?
Expected this to be a locked down chrome instance that can be used in a terminal where users interact with the screen to type in information.
[Please be as specific as possible here]

#### What did you expect to happen?
not beeing able to leave the current page.
#### What happened instead?
im able to open new tabs with ctrl+t and navigate in chromium freely. 
#### Version of FullPageOS?
latest as of 2023-12-15
[Can be found in /etc/fullpageos_version ALWAYS INCLUDE.]

#### Screenshot(s) showing the problem:

[If applicable. Always include if unsure or reporting UI issues.]

**Comment by guysoft** [comment] 2024-01-15 12:53
Duplicate of #264

**Closed by guysoft** 2024-01-15 12:53 UTC
