### ISSUE TITLE
using 2 screens on raspberry pi 4

### ISSUE THREAD

**Issue by JayBird77** [guysoft/FullPageOS#501] opened 2024-01-11 20:57 UTC
I want to be able to use 2 screens, but when I plug the second monitor/tv in it looks great except the touchscreen I want to use is off. I assume both displays need to be set to the same resolution? How do I make this work for me?

**Comment by guysoft** [comment] 2024-01-14 14:30
Duplicate of :
https://github.com/guysoft/FullPageOS/issues/302

You can also post there how you managed to use two screens. Because there are several ways to do it.

**Closed by guysoft** 2024-01-14 14:30 UTC
