### ISSUE TITLE
Rotating the screen 180 Degrees

### ISSUE THREAD

**Issue by conrad9900** [guysoft/FullPageOS#181] opened 2017-11-01 11:11 UTC
#### What were you doing?

Trying to Rotate 180, i added lcd_rotate=2 to boot/config

#### What did you expect to happen?

180 rotation

#### What happened instead?

touchscreen changed but not screen

#### Version of FullPageOS?

[Can be found in /etc/fullpageos_version ALWAYS INCLUDE.]

#### Screenshot(s) showing the problem:

[If applicable. Always include if unsure or reporting UI issues.]

**Comment by guysoft** [comment] 2017-11-01 14:21
Duplicate ofhttps://github.com/guysoft/FullPageOS/issues/137

**Closed by guysoft** 2017-11-01 14:21 UTC
