### ISSUE TITLE
Raspberry Pi 3 B+ Custom FullPageOS create 

### ISSUE THREAD

**Issue by nscpro** [guysoft/FullPageOS#287] opened 2019-07-19 12:24 UTC
Hi.

If i'm using this guide:

sudo apt-get install realpath p7zip-full qemu-user-static

git clone https://github.com/guysoft/CustomPiOS.git
git clone https://github.com/guysoft/FullPageOS.git
cd FullPageOS/src/image
wget -c --trust-server-names 'https://downloads.raspberrypi.org/raspbian_lite_latest'
cd ..
../../CustomPiOS/src/update-custompios-paths
sudo modprobe loop
sudo bash -x ./build_dist

I get a finally this error. 

++++ sfdisk -d 2019-07-10-raspbian-buster-lite.img
++++ grep 2019-07-10-raspbian-buster-lite.img2
++++ awk '{print $4-0}'
+++ start=540672
+++ offset=276824064
+++ detach_all_loopback 2019-07-10-raspbian-buster-lite.img
++++ losetup
++++ grep 2019-07-10-raspbian-buster-lite.img
++++ awk '{ print $1 }'
+++ for img in $(losetup  | grep $1 | awk '{ print $1 }' )
+++ losetup -d /dev/loop0
losetup: /dev/loop0: detach failed: No such device or address
+ exit 1

What can i do to fix this problem and where is locate final file what i put another MicroSD card?

Thank you.

**Comment by guysoft** [comment] 2019-08-05 14:06
Duplicate of:
https://github.com/guysoft/CustomPiOS/issues/55

**Closed by guysoft** 2019-08-05 14:06 UTC
