### ISSUE TITLE
"Can't update Chromium" message inside browser

### ISSUE THREAD

**Issue by papierkorb27** [guysoft/FullPageOS#327] opened 2020-06-03 06:49 UTC
Running the kiosk-pi with FullPageOS I got the message "Can't update Chromium" inside Chromium some hours after booting. That seems to be an annoying Chromium bug. Maybe its interesting for FullPageOS users to know this workaround until the bug will be fixed: https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=264399&start=50

`sudo touch /etc/chromium-browser/customizations/01-disable-update-check;echo CHROMIUM_FLAGS=\"\$\{CHROMIUM_FLAGS\} --check-for-update-interval=31536000\" | sudo tee /etc/chromium-browser/customizations/01-disable-update-check`

**Comment by guysoft** [comment] 2020-06-09 23:01
You are welcome to make a pull request

**Comment by markgaze** [comment] 2020-06-15 13:44
This was fixed in #317 ?

**Comment by guysoft** [comment] 2020-06-15 14:16
@markgaze That issue is unrelated, its about the splash screen before chromium starts.

**Comment by markgaze** [comment] 2020-06-15 14:26
@guysoft whilst that is true, it also fixed #319 which I think this is a duplicate of? Apologies if this is a slightly different issue!

**Comment by guysoft** [comment] 2020-06-15 14:33
@markgaze Indeed it did, I didn't read though all the issue.
Ok, cool, thanks for helping me tidy up!

**Closed by guysoft** 2020-06-15 14:33 UTC

**Comment by markgaze** [comment] 2020-06-15 14:34
> @markgaze Indeed it did, I didn't read though all the issue.
> Ok, cool, thanks for helping me tidy up!

Any time! Thanks for maintaining this project which makes my life much easier! 😁
