### ISSUE TITLE
touch itself won't rotate

### ISSUE THREAD

**Issue by gohigher14** [guysoft/FullPageOS#458] opened 2023-03-23 13:09 UTC
#### What were you doing?

i'm using an lcd screen connected with hdmi and an usb touchscreen on top.
My image is already turned the correct way , but the touch itself isn't.
In my boot/conf.txt i've added :
display_hdmi_rotate=2
lcd_rotate=3 
Tried lcd_rotate= with 0 , 1, 2 and 3 . Nothing happens.

#### What did you expect to happen?
Touchscreen itself to turn the correct way

#### What happened instead?
It stays the same

#### Version of FullPageOS?

0.13.0

**Comment by guysoft** [comment] 2023-03-24 15:45
Duplicate of #137

**Closed by guysoft** 2023-03-24 15:45 UTC
