### ISSUE TITLE
Does not respect lcd_rotate?

### ISSUE THREAD

**Issue by Jaxel** [guysoft/FullPageOS#188] opened 2017-11-22 22:54 UTC
I'm running this on the official Raspberry Pi Touchscreen. That screen requires you to use `lcd_rotate=2` when put into a case. However, this OS does not respect the rotation and is showing upside down.

**Comment by guysoft** [comment] 2017-11-23 00:47
Duplicate of #137

**Closed by guysoft** 2017-11-23 00:47 UTC
