### ISSUE TITLE
FullPageOS Chromium Browser show "Aw Snap" crash every little bit

### ISSUE THREAD

**Issue by nscpro** [guysoft/FullPageOS#301] opened 2019-11-07 17:57 UTC
I'm using "2019-07-15_2019-07-10-fullpageos-buster-lite-0.11.0.zip" but my web page every little bit crash and show "Aw Snap". How to fix this or is there another browser that doesn't crash?

**Comment by nscpro** [comment] 2019-11-07 18:53
If the FullPageOS Scripts folder has files "Refresh" etc..so why it doesn't automatically refresh when "Aw Snap" error message comes up. also the chromium_debug log file says it does not exist.

**Comment by guysoft** [comment] 2019-11-10 09:13
@nscpro It doesn't because that is not the default behaviour.

See #294 and #275

This is a duplicate of those, so please continue talks there.

**Closed by guysoft** 2019-11-10 09:13 UTC
