### ISSUE TITLE
Cursor not hiding

### ISSUE THREAD

**Issue by slindgren** [guysoft/FullPageOS#15] opened 2016-03-15 20:31 UTC
I've noticed that the Cursor doesn't seem to be hiding itself after loading web page.

**Comment by guysoft** [comment] 2016-03-15 20:36
I am not sure how to fix that, nor do I have the research time. A pull request would help.

**Comment by slindgren** [comment] 2016-03-15 21:06
It would be enough if the cursor would move away, or just move a bit sometimes. Then the Chromium + css should know how to hide it.. I think..

**Comment by guysoft** [comment] 2016-04-03 14:01
There was a pull request fixing this issue. Is this fixed in the nightly?

**Comment by slindgren** [comment] 2016-04-03 18:30
I have not downloaded the new nightly, but I'll get it tomorrow and check if everything is working!

**Comment by slindgren** [comment] 2016-04-04 15:11
now it requires login and the chromium isn't starting.. :/

**Comment by guysoft** [comment] 2016-05-27 22:34
I just tested, it still does not work, try latest nightly

**Comment by tailorvj** [comment] 2016-06-02 16:59
@guysoft I found this solution on AskUbuntu:
Try 'unclutter'
the purpose of this program is to hide the pointer after the mouse has not moved for a while. Using it, you can make the pointer appear only when the user touches the screen, and disappear right after it. (maybe this was not exactly what you were aiming for. But it is much easier than your alternative =P)
To use, install it
`sudo apt-get install unclutter`
then run it
`unclutter -idle 0.01 -root`
the number is a number of seconds before the pointer disappears (in this case, 1/100 seconds)

**Comment by pricecomstock** [comment] 2016-06-04 23:00
If you're getting "Could not open display" from unclutter, try the following.
`DISPLAY=:0.0 ; export DISPLAY
unclutter -idle 0.01 -root`

Hopefully that saves you a trip to [this thread.](https://www.reddit.com/r/Fedora/comments/1f58qf/remove_mouse_cursor_on_boot/)

**Comment by andreicek** [comment] 2016-06-08 06:56
If you want this done automatically on boot (or to be precise when X becomes available) you can add this to `/etc/X11/xinit/xinitrc`

So your file might look like this:
```
#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script
. /etc/X11/Xsession
unclutter -idle 0.01 -root
```

**Comment by guysoft** [comment] 2016-06-16 14:47
Likely this has been fixed by #34 , if not then we are going to add in 0.7.0 unclutter

**Comment by guysoft** [comment] 2017-09-26 11:08
We didn't add unclutter and this seems to be working.

**Closed by guysoft** 2017-09-26 11:08 UTC
Labels: bug

**Comment by G3z** [comment] 2018-02-16 14:35
simply edited lightdm config in 
`/etc/lightdm/lightdm.conf`

changing line
`#xserver-command=X`
to
`xserver-command=X -nocursor`

**Comment by guysoft** [comment] 2018-02-16 19:10
Cool to know, but that would hide the cursor all together

**Comment by slindgren** [comment] 2018-02-16 19:10
Tätä sähköpostiosoitetta ei enää käytetä! Löydät uuden sähköpostiosoitteen Jumppahullun nettisivuilta!
  
 Ystävällisin terveisin
 Samuli Lindgren

**Comment by G3z** [comment] 2018-02-16 19:13
@guysoft yes but touch still works fine, it depends on what is the desired effect.

**Comment by maxcel2** [comment] 2022-12-03 16:45
I know that this is an old thread, but I'm still having a problem getting rid of the cursor in FullPageOS. G3z's solution of editing the lightdm.conf file doesn't do anything. 
Installing unclutter and running it from the command line brings up the cursor while the screen is touched, which then disappears quickly, as intended. However, if it is added to xinitrc, the cursor hangs around for about a second. 
I really want to get rid of the cursor altogether because the tip of the arrow is offset from the point of stylus contact and I have been unsuccessful so far in calibrating the screen.

**Comment by Azarmcshane** [comment] 2025-08-18 14:04
I am such a noob here, what do I do with info? just want to do away with the cursor, not sure what or where to edit, is it assumed that every one understands what do do with this info? 

simply edited lightdm config in
/etc/lightdm/lightdm.conf

changing line
#xserver-command=X
to
xserver-command=X -nocursor

**Comment by 90nicho** [comment] 2025-10-03 08:48
> I am such a noob here, what do I do with info? just want to do away with the cursor, not sure what or where to edit, is it assumed that every one understands what do do with this info?
> 
> simply edited lightdm config in /etc/lightdm/lightdm.conf
> 
> changing line #xserver-command=X to xserver-command=X -nocursor

I struggled with this too as there's a lot of assumed knowledge, when SSH-ing in to the pi, I couldn't see the etc folder when using dir or ls, so didn't know I could use the command:
```
sudo nano /etc/lightdm/lightdm.conf`
```
this will allow you to edit the file, you can then add the line below (or uncomment the existing line and add the "-nocursor" part)
```
xserver-command=X -nocursor
```
reboot and there's no cursor

**Comment by milansimek** [comment] 2025-12-18 22:58
In my case adding the `--cursor=none` flag to `/home/USER_NAME/scripts/start_chromium_browser` did the trick.

EDIT: 
I also had to install `unclutter-xfixes` (`sudo apt install unclutter-xfixes`) and add this line below the shebang line in `/home/USER_NAME/scripts/start_chromium_browser`: 

`unclutter-xfixes --timeout 0 --hide-on-touch &` 

(regular unclutter did not work correctly for me)

**Comment by kurtnelle** [comment] 2026-01-14 03:51
> In my case adding the `--cursor=none` flag to `/home/USER_NAME/scripts/start_chromium_browser` did the trick.
> 
> EDIT: I also had to install `unclutter-xfixes` (`sudo apt install unclutter-xfixes`) and add this line below the shebang line in `/home/USER_NAME/scripts/start_chromium_browser`:
> 
> `unclutter-xfixes --timeout 0 --hide-on-touch &`
> 
> (regular unclutter did not work correctly for me)

Works!
