### ISSUE TITLE
Touchscreen controls don't rotate properly in vertical/portrait mode?

### ISSUE THREAD

**Issue by Jaxel** [guysoft/FullPageOS#191] opened 2017-11-26 21:48 UTC
Adding the following to my "boot/config.txt":

    display_rotate=1

This rotates the screen well. However, the actual touchscreen controls don't rotate. The touchscreen controls only properly rotate on "2" (180deg); but not on "1" (90deg) or "3" (270deg). Are there any solutions for this?

**Comment by guysoft** [comment] 2018-01-07 12:40
Could this be a duplicate of https://github.com/guysoft/FullPageOS/issues/137 ?

**Comment by guysoft** [comment] 2018-02-05 13:38
Closing as duplicate

**Closed by guysoft** 2018-02-05 13:38 UTC
