### ISSUE TITLE
Not running a webserver by default

### ISSUE THREAD

**Issue by thedumbterminal** [guysoft/FullPageOS#411] opened 2022-03-05 17:18 UTC
#### What were you doing?

After a fresh install I noticed a web server was running on port 80. But this distro is generally used for loading a remote URL according to the docs.

#### What did you expect to happen?

No web server by default

#### What happened instead?

lighttpd was running,

I had to run:

```
sudo apt-get remove lighttpd
```

To remove it.

#### Version of FullPageOS?

0.12.0

**Comment by guysoft** [comment] 2022-03-05 18:05
Working as intended. Wontfix.
As listed in the features, FullPageOS comes with a default app called FullPageDashboard that serves a tab manager. see:
https://github.com/guysoft/FullPageOS#features

**Closed by guysoft** 2022-03-05 18:05 UTC
