### ISSUE TITLE
Hide / disable side scrollbar

### ISSUE THREAD

**Issue by TiWe1998** [guysoft/FullPageOS#413] opened 2022-03-15 08:05 UTC
Hello. 

Can I actually disable the scrollbars now? When I take this guide, it tells me that the file does not exist. Is that out of date?

Old guide: https://github.com/guysoft/FullPageOS/wiki

BR

**Comment by guysoft** [comment] 2022-03-15 11:32
Hey,
1. That guide is not old, I updated it today. But I see no scrollbars answer in the FAQ - what are you looking at?
2. duplicate of https://github.com/guysoft/FullPageOS/issues/32

**Closed by guysoft** 2022-03-15 11:32 UTC

**Comment by TiWe1998** [comment] 2022-03-15 12:56
Yes, that's what I mean. But I can't find _/etc/chromium-browser/customizations/00-rpi-vars_ on my Raspberry.
