### ISSUE TITLE
Pi will not accept static IP

### ISSUE THREAD

**Issue by conrad9900** [guysoft/FullPageOS#215] opened 2018-03-12 16:47 UTC
#### What were you doing?

Trying to assign a static IP address, I have disabled DHCP in all the places i can think of but it still will not accept my static and assign a dhcp address

#### What did you expect to happen?

A static address to be assigned

#### What happened instead?

A DHCP address was assigned

#### Was there an error message displayed? What did it say?

No error, just wrong address

#### Version of FullPageOS?

0.8.1 22/10/17
#### Screenshot(s) showing the problem:

 You can use this file to manually set up your network configuration.
#
# This file is included into /etc/network/interfaces, so anything that
# works by editing that file is also possible here.

### WIFI CONFIGURATION ######################################################
# The three segments below should cover you in most cases if you run
# a wifi network that uses either WPA/WPA2 or WEP encryption.
#
# Just uncomment the lines prefixed with a single # of the configuration
# that matches your wifi setup and fill in SSID and passphrase.

## WPA/WPA2 secured
#iface wlan0-fullpageos inet manual
#    wpa-ssid "put SSID here"
#    wpa-psk "put password here"

## WEP secured
#iface wlan0-fullpageos inet manual
#    wireless-essid "put SSID here"
#    wireless-key "put password here"

## Open/unsecured
#iface wlan0-fullpageos inet manual
#    wireless-essid "put SSID here"
#    wireless-mode managed

### WIRED CONFIGURATION #####################################################
# The following segment allows you to configure your wired connection
# with a static IP.
#
# Just uncomment the lines prefixed with a single #. Then connect
# a cable to the Pi and another system, e.g. a Laptop, and set that
# other system's network configuration to:

#   address:   192.168.10.7
#   netmask:   255.255.255.0
#   broadcast: 192.168.10.21
#
# You can then reach the Pi from the system's browser by going to
#
#   http://192.168.250.1
#
# or
#
#   http://fullpageos.local

iface eth0:1 inet static
	address: 192.168.10.7
	netmask: 255.255.255.0
	broadcast: 192.168.10.255
	domain: ad.prodev.ie
	dns-nameservers: 192.168.10.21

**Comment by guysoft** [comment] 2018-03-12 22:35
Duplicate of #130 which you also opened, got an answer for, said thanks, and then ignored.

**Closed by guysoft** 2018-03-12 22:35 UTC
