### ISSUE TITLE
update for Raspberry PI 5 (Bookworm)

### ISSUE THREAD

**Issue by Speedymatze** [guysoft/FullPageOS#498] opened 2024-01-05 18:01 UTC
I would like to use a Raspberry PI 5, is a new version possible?

**Comment by guysoft** [comment] 2024-01-05 21:50
Yes, I just started a nightly build (they are built on demand). If it passes it should be up and available shortly.
Since there is demand I think if its functional I will open a release candidate and you can review it for release.
Related #497

**Comment by Speedymatze** [comment] 2024-01-06 16:00
That's great, but I can't find the "nightly build". Where can I download it? Or did the build not work?

**Comment by guysoft** [comment] 2024-01-06 22:48
The build failed. Apt call failed on internet request. Will try again. And if that fails will look in to it tomorrow

**Comment by lokomoti** [comment] 2024-01-31 20:27
I would also appreciate working image for Pi 5. Should I stay on Pi 4 until it gets released?

**Comment by 1liminal1** [comment] 2024-02-20 03:34
So does this work on the 5 yet?

**Comment by guysoft** [comment] 2024-02-20 11:50
@1liminal1 There is a nightly build which I didn't get to test. If you want to test it that would help!
I hope to get time to test it soon. I have to do that both for FullPageOS and OctoPi. Now that the build system seems to be working.

**Comment by 1liminal1** [comment] 2024-02-20 23:15
Thanks! Im happy to test. I did see nightly builds in the Raspberry Pi image flasher (cant remember the date though) Is that were to get it?

**Comment by 1liminal1** [comment] 2024-02-21 11:13
Ok, so I installed the nightly from the 19th and it didn't work, it booted to a login page, I logged in and got nothing on the screen except a kinda Debian background. Then it shut off and pressing the buttion the green light would come on for a sec and flash like it was reading the card. Then turn red again. Im new to the Pi 5, so it would have a red steady light and nothing on the screen. 

Also it did not seem to connect to the wifi? I added my config though the pi flashing app and the user was correct, but wifi didnt work.

**Comment by guysoft** [comment] 2024-02-21 16:12
Ok, the issue is the /boot files, I will fix it.

**Comment by 1liminal1** [comment] 2024-02-21 22:27
Awesome! Thanks

Let me know where to get the build from? 🙂
________________________________

**Comment by 1liminal1** [comment] 2024-02-21 22:29
Also, can I use the wifi ssh settings from the flasher, or do I need to edit the fullpageos-wpa-suplicant? (from memory, it was something like that anyway :)

**Comment by guysoft** [comment] 2024-02-24 12:24
Ok, the latest nightly from 2023-02-23 boots for me and loads the welcome page (note there were a few builds that day, so make sure to take the latest one). I tested with a Pi 5.

I had to update a few things in CustomPiOS, you are  welcome to test and report now.

**Comment by 1liminal1** [comment] 2024-02-24 23:55
Oh ok, sorry, I didn't hear back and needed to keep moving, so ended up setting up with native Raspbian :)

**Comment by tzvigqb** [comment] 2024-02-27 22:00
@guysoft I'm having the same issue as @1liminal1, using the latest version from [here](https://unofficialpi.org/Distros/FullPageOS/nightly/?C=M;O=D). Am I missing something?
Thanks!

**Comment by guysoft** [comment] 2024-02-27 22:10
Dont set the username to anything other that "pi". There is a bug if its chaged #432

**Comment by tomm144** [comment] 2024-03-12 13:08
Temporary solution (wokred for me) - https://chromewebstore.google.com/detail/framer-make-iframes-possi/adohambhfalbpaenaclmhhjhilmakmoo

**Comment by guysoft** [comment] 2024-04-07 13:59
Tested, works, closing.

**Closed by guysoft** 2024-04-07 13:59 UTC
